[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
once_cell = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "=1.0.209", features = ["derive"] }
serde_json = "1.0"
#处理日期的库
chrono = "0.4"
